apiVersion: v1
kind: PersistentVolume
metadata:
  name: accounting-sql-db-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: accounting-pd
    fsType: pd-standard
