apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecais
  name: accounting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-service
  template:
    metadata:
      labels:
        app: accounting-service
    spec:
      containers:
        - name: accounting-service-container
          image: clawcastle/accounting:v1
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: ACCOUNTING_SA_PASSWORD
              value: Password_1234
---
apiVersion: v1
kind: Service
metadata:
  name: accounting-loadbalancer
  namespace: tecais
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: accounting-service
