apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecais
  name: charging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charging-service
  template:
    metadata:
      labels:
        app: charging-service
    spec:
      containers:
        - name: charging-service-container
          image: clawcastle/charging-service:v1
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: charging-loadbalancer
  namespace: tecais
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: charging-service
