apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecais
  name: electricity-consumption-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electricity-consumption-submission
  template:
    metadata:
      labels:
        app: electricity-consumption-submission
    spec:
      containers:
        - name: electricity-consumption-submission-container
          image: clawcastle/electricity-consumption-submission:v1
          ports:
            - containerPort: 80
