apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: services
  name: electricity-consumption-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electricity-consumption-submission
  template:
    metadata:
      labels:
        app: electricity-consumption-submission
    spec:
      containers:
        - name: electricity-consumption-submission-app
          image: clawcastle/electricityconsumption:v1
          ports:
            - containerPort: 80
