apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecais
  name: heat-consumption-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heat-consumption-submission
  template:
    metadata:
      labels:
        app: heat-consumption-submission
    spec:
      containers:
        - name: heat-consumption-submission-app
          image: clawcastle/heat-consumption-submission:v1
          ports:
            - containerPort: 80
