kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: rabbit-mq-pvc
    spec:
      capacity:
        storage: 1Mi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      gcePersistentDisk:
        pdName: rabbitmq-persistent-storage
        fsType: nfs4
