apiVersion: v1
kind: Service
metadata:
  name: service-message-bus
  namespace: tecais
spec:
  type: ExternalName
  externalName: rabbitmq.rabbitmq.svc.cluster.local
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
