apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-db
  template:
    metadata:
      labels:
        app: status-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: pass1234
          volumeMounts:
            - name: status-sql-db
              mountPath: /var/opt/mssql
      volumes:
        - name: status-sql-db
          persistentVolumeClaim:
            claimName: status-sql-data
---
apiVersion: v1
  selector: status-sqlserver
kind: Service
metadata:
  name: status-sqlserver
spec:
    app: status-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: status-sql-data
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: status-sql-db
    fsType: nfs4
