apiVersion: v1
kind: PersistentVolume
metadata:
  name: status-sql-db-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: status-sql-db
    fsType: pd-standard
