apiVersion: v1
kind: PersistentVolume
metadata:
  name: status-sql-db-pv
  namespace: tecais
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: status-sql-db
    fsType: nfs4
