apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecais
  name: water-consumption-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: water-consumption-submission
  template:
    metadata:
      labels:
        app: water-consumption-submission
    spec:
      containers:
        - name: water-consumption-submission-app
          image: clawcastle/waterconsumption:v1
          ports:
            - containerPort: 80
